
language: cpp

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - GCC_VER="9"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"

      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
            - g++-9
            - cmake
            - libgtkmm-3.0-dev
            - libwebkit2gtk-4.0-dev
            - fakeroot
            - debhelper

before_script:
  - eval "${MATRIX_EVAL}"
  - cmake --version
  # - mkdir -p build/debug
  # - mkdir -p build/release

script:
  # - cd build/debug
  # - cmake -j2 -DCMAKE_BUILD_TYPE=Debug ../..
  # - make
  # - cd ../release
  # - cmake -j2 -DCMAKE_BUILD_TYPE=Release ../..
  # - make
  - dpkg-buildpackage -us -ui -uc

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: ../whatsapp-for-linux_1.0.6_amd64.deb
  skip_cleanup: true
  draft: true
  on:
    tags: true